firehol/firehol

- sbin/firehol.in
- sbin/fireqos.in
- sbin/link-balancer.in
The whole FireHOL suite supports internally 2 types of marks: usermarks and connmarks.
Connmarks are used by link-balancer to mark the interfaces traffic came in order to send the replies back via the same path. All tools support (by default) 64 connmarks.
Usermarks are used by all tools to mark traffic the user wants. The mark firehol helper, the mark firehol match, the mark fireqos match and the mark link-balancer policy based routing match, they all refer to usermarks. All tools support (by default) 128 usermarks.
Marks and connmarks are now bitmasked and co-exist. FireHOL always saves and restores marks for each connection. New marks are assigned on NEW connections and saved to connection state when the packet leaves the machine. Marks are restored on ESTABLISHED and RELATED …
> marks and connmarks bitmasking; custom mark types

- sbin/firehol.in
Without setting `$firewall_policy6_applied` firehol would print the
following error message during explain:
> /usr/sbin/firehol: line 3667: [: -eq: unary operator expected
The default definition of `$firewall_policy6_applied` is not executed
in explain mode (like the definition in `$firewall_policy_applied`) and
`$firewall_policy6_applied` is undefined in line 3667.
> Set missing variable for IPv6

- sbin/firehol.in
When running the wizard or helpme I only got eth0 as interface, but I had more interfaces. So I went the FOSS way, and fixed it in the source.
> Strip out NONE from sit0NONE in the wizard/helpme

- doc/fireqos/fireqos-params-match.5.md
- sbin/fireqos.in
I've added DSCP matching support for FireQOS. As tc-filter right now only understands TOS values, FireQOS will just convert the configured DSCP value (AF31, EF, ...) to their coresponding TOS hex value.
> DSCP matching support

- doc/fireqos/fireqos-params-match.5.md
- doc/links-keywords-fireqos
- sbin/fireqos.in
- sbin/update-ipsets.in
I ported some of the functionality of my MasterShaper project into FireQOS to support matching IP addresses, protocols, ports and TOS fields within an GRE-encapsulated packet.
In my situation I have a big bunch of GRE-over-IPsec tunnels which would lead to thousands of tc-filter rules being loaded per GRE interface. Instead tc-filter dives a bit deeper into the IP packet and matches the packets attribute within the GRE packet.
> match encapsulated packet inside GRE

- sbin/Makefile.am
This patch forces to install the library part in an architecture independent folder-tree, what make great sense for a script library.
> enforced arch indep libdir

- contrib/firehol.service
- contrib/fireqos.service
i was comparing systemd files from fedora git repo and noticed some differences.
the other diff was `After=network.target`, wasn't sure about that
> add man:fireqos.conf

- doc/firehol/firehol-defaults-conf.5.md
Description: source typo
Correct spelling errors as reported by lintian in the manpages; meant
to silence lintian and eventually to be submitted to the upstream maintainer.
Origin: vendor, Debian
Comment: spelling-error-in-manpage
Author: Jerome Benoit <calculus@rezozer.net>
Last-Update: 2016-11-22
> Fix typo as detected by lintian

- sbin/firehol
- Fixed to behave as described in the doc: https://firehol.org/firehol-manual/firehol-blacklist/
- Keep historical bug to avoid existing configuration breakage
NOTE: this is really a blind change
> Align code with firehol-blacklist(5) doc

- .travis.yml
- .travis/decrypt-if-have-key
- .travis/deploy-if-have-key
Github/travis integration does not make available the encryption keys
for pull requests from remote repositories. Move direct commands from
travis into scripts so that we decrypt and deploy only when we can.
> Fix pull requests from external repositories

- examples/fireqos-multiple-organizations.conf
Description: ambiguous shebang in FireQOS example: discard
Discard the ambiguous (and likely forgotten) shebang as detected by lintian
in the FireQOS example multiple-organizations.conf ; meant to silence lintian
and eventually to be submitted to the upstream maintainer.
Origin: vendor, Debian
Comment: example-unusual-interpreter example-interpreter-not-absolute
Author: Jerome Benoit <calculus@rezozer.net>
Last-Update: 2017-01-21
> discard ambiguous shebang in fireqos example

- doc/firehol/contents.tpl
- doc/fireqos/contents.md
- doc/vnetbuild/contents.md
Description: update: documentation: Copyrigh year bump
Bump to 2017 the Copyrigt year in documentation; meant to be submitted to
the upstream maintainer.
Origin: vendor, Debian
Author: Jerome Benoit <calculus@rezozer.net>
Last-Update: 2017-01-21
> bump copyright year in documentation

- sbin/firehol
Clean up iptables-save output to eliminate things that change per-run:
- Remove timestamp from comments
- Always write out counters as 0
> Make saved firewall contents reproducible

- sbin/firehol
- tests/firehol/basics/interface.aud4
- tests/firehol/basics/interface.aud6
- tests/firehol/basics/interface46.aud4
- tests/firehol/basics/interface46.aud6
- tests/firehol/basics/router.aud4
- tests/firehol/basics/router.aud6
- tests/firehol/basics/router46.aud4
- tests/firehol/basics/router46.aud6
- tests/firehol/not-both/ipv4-disable-conf.aud6
- tests/firehol/not-both/ipv4-disable-defaults.aud6
- tests/firehol/not-both/ipv6-disable-conf.aud4
- tests/firehol/not-both/ipv6-disable-defaults.aud4
FIREHOL_DROP_ORPHAN_TCP_* options generate a number of iptables drop
rules. This means that even an 'accept' policy, let alone the more
common 'client all accept', still applies filtering to the [output of the]
interface. Since these commands are described as suppressing log noise, the
only important item is that they be included before the log invalid/reject
action.
It is relatively desirable not to disable these options, as they are possibly useful on
other interfaces/traffic flows.
Refactor firewall_filtering_policy_common to break these out into a 'late'
version, and include that in user chains that do not end accept/return, as
well as in the main INPUT/OUTPUT/FORWARD chains *after* jumps to user chains.
Notably this fixes the NFS client, at least as tested on the Debian Stretch …
> Include user policies in chains before handling orphans

- sbin/update-ipsets
DShield have [announced that they require scripts to include a URL or email address](https://www.dshield.org/forums/diary/Read+This+If+You+Are+Using+a+Script+to+Pull+Data+From+This+Site/22402/) in user agent strings from now on to be permitted to download things.
I've changed `geturl` to use a new variable `USER_AGENT` and have added the firehol homepage URL to it.
> include URL in user agent string in update-ipsets

- sbin/fireqos
Hi, very minor update - I noticed the Google Hangouts ports for UDP were missing three, so I expanded the range.  TCP is fine.  Reference is here:
https://support.google.com/a/answer/1279090
> Expanding Google Hangouts UDP port range by 3

- sbin/firehol
#114 
This PR adds a new helper, named `docker_bridge`.
It is used like this:
```
docker_bridge INTERFACE SUBNET
```
where `INTERFACE` is usually `docker0` and `SUBNET` is `172.17.0.0/16`.
The helper will setup the basic functionality docker requires:
1. setup `nat/DOCKER`, `filter/DOCKER`, `filter/DOCKER-USER`, `filter/DOCKER-ISOLATION` chains
2. provide static defaults for all these chains
3. allow the host to reach the containers
4. allow the containers to use the internet
5. allow the containers to talk to each other
> The helper **does not** setup any port mappings, and **does not** add any useful rules under any of the docker chains. The only way to get these rules after a firewall restart, is to also restart docker.
The helper can safely be called many times to setup multiple …
> add docker_bridge helper; support newer iptables versions

- sbin/firehol
- tests/firehol/basics/empty.aud4
- tests/firehol/basics/empty.aud6
- tests/firehol/basics/interface.aud4
- tests/firehol/basics/interface.aud6
- tests/firehol/basics/interface46.aud4
- tests/firehol/basics/interface46.aud6
- tests/firehol/basics/router.aud4
- tests/firehol/basics/router.aud6
- tests/firehol/basics/router46.aud4
- tests/firehol/basics/router46.aud6
- tests/firehol/not-both/ipv4-disable-conf.aud6
- tests/firehol/not-both/ipv4-disable-defaults.aud6
- tests/firehol/not-both/ipv6-disable-conf.aud4
- tests/firehol/not-both/ipv6-disable-defaults.aud4
In many cases, for auditing reasons we add log lines to verify connections have been established.
An easy way to do it, is by adding this at the top of firehol.conf:
```sh
action AUDIT_ACCEPT \
action ACCEPT state NEW log "AUDIT ACCEPT" \
next action ACCEPT
```
So, we can later use `server xxx AUDIT_ACCEPT`.
In such cases, the indirectly dropped packets which are logged without any positive or negative indication, are often misinterpreted. 
This PR, adds `BLOCKED` or `UNMATCHED` to all such log lines, to make it clear that these logs have actually blocked traffic.
> explicitly logs BLOCKED or UNMATCHED when dropping packets

- sbin/firehol
The file /proc/sys/net/netfilter/nf_conntrack_max never exists in
a namespace (either it is not settable there, or no-one has implemented
it yet).
Check for a file which does get created in the namespace when netfilter
is available instead.
> Fix wait for netfilter ready when using namespaces

- sbin/firehol
fixes #272 
```
FireHOL: Saving active firewall to a temporary file...  OK 
FireHOL: Processing file '/etc/firehol/firehol.conf'...  OK  (772 iptables rules)
Your firewall is ready to be fast-activated...
If you don't continue, no changes will have been made to your firewall.
Activate the firewall? (just press enter to confirm or Control-C to stop) : 
FireHOL: Activating ipsets...  OK 
FireHOL: Fast activating new firewall...  OK 
FireHOL: Executing postprocess2 commands...  OK 
Keep the firewall? (type 'commit' to accept - 30 seconds timeout) : commit 
Successfull activation of FireHOL firewall.
FireHOL: Saving activated firewall to '/var/spool/firehol'...  OK 
```
Added this:
```
FireHOL: Executing postprocess2 commands...  OK 
```
> added postprocess2 to execute commands, after firewall activation

- sbin/firehol
- tests/firehol/basics/interface.aud4
- tests/firehol/basics/interface.aud6
- tests/firehol/basics/interface46.aud4
- tests/firehol/basics/interface46.aud6
- tests/firehol/basics/router.aud4
- tests/firehol/basics/router.aud6
- tests/firehol/basics/router46.aud4
- tests/firehol/basics/router46.aud6
- tests/firehol/not-both/ipv4-disable-conf.aud6
- tests/firehol/not-both/ipv4-disable-defaults.aud6
- tests/firehol/not-both/ipv6-disable-conf.aud4
- tests/firehol/not-both/ipv6-disable-defaults.aud4
This PR adds a new configuration option:
```sh
FIREHOL_DROP_INVALID_ACTION="DROP"
```
The user may change this setting to `REJECT` traffic.
This is required in long-living sockets that once removed from the connection tracker, they had to timeout. By setting this to `REJECT`, the invalid packet will be rejected, allowing the remote end to clean up faster.
> allow DROP_INVALID with any action (e.g. REJECT)

- sbin/firehol
- tests/firehol/basics/empty.aud4
- tests/firehol/basics/empty.aud6
- tests/firehol/basics/interface.aud4
- tests/firehol/basics/interface.aud6
- tests/firehol/basics/interface46.aud4
- tests/firehol/basics/interface46.aud6
- tests/firehol/basics/router.aud4
- tests/firehol/basics/router.aud6
- tests/firehol/basics/router46.aud4
- tests/firehol/basics/router46.aud6
- tests/firehol/not-both/ipv4-disable-conf.aud6
- tests/firehol/not-both/ipv4-disable-defaults.aud6
- tests/firehol/not-both/ipv6-disable-conf.aud4
- tests/firehol/not-both/ipv6-disable-defaults.aud4
The a router is set to policy reject, the RST packets are not sent back to the clients. They are dropped at OUTPUT interface.
This PR adds option:
```sh
FIREHOL_ACCEPT_OUTPUT_UNMATCHED_TCP_RST=0
```
When set to 1, the firewall will allow all OUTPUT TCP packets with RST in them.
> added option FIREHOL_ACCEPT_OUTPUT_UNMATCHED_TCP_RST

- sbin/link-balancer
fix link balancer and ignore linkdown. with linkdown, routes can not be added or deleted as they are marked invalid
> Issue #211. fix link balancer and ignore linkdown

- sbin/update-ipsets
There was a condition that affects merged ipsets: if for any reason, the `.cache` file that update-ipsets saves in `/etc/firehol/ipsets` gets deleted or corrupted, merged ipsets fail to detect the presence of ipsets and produce merged ipsets with missing ingredients.
This PR attempts to detect this, and force reprocessing of the ipsets that somehow got lost from the `.cache` file.
> update-ipsets: detect the need to reprocess an ipset

- contrib/firehol.service
As the title goes.
With this patch I can just run `systemctl reload firehol` to reload the config, which only runs `firehol start` without having to stop the firewall first.
> firehol.service: Use `firehol start` for  ExecReload=

- sbin/firehol
I noticed that outbound TCP connections to blacklisted hosts were timing out rather than being rejected, I've added a `REJECT with tcp-reset` rule for outbound blacklists, which solved my problem.
---
Before using the `blacklist` directives, I had rules like this (my DNS blacklisting mechanism resolves to bogus hosts in these two IP ranges):
```
interface4 any if_blackhole
policy return
client all reject dst "192.0.2.0/24"
interface6 any if6_blackhole
policy return
client all reject dst "100::/8"
...
router4 rt_blackhole dst "192.0.2.0/24"
route all reject
router6 rt6_blackhole dst "100::/8"
route all reject
```
With the patch in this pull request, I can reduce it to this, and have identical behavior (TCP resets + ICMP host unreachable for everything else):
```
ipset4 create …
```
> blacklist: reject with tcp-reset for outbound TCP connections

- doc/firehol/firehol-blacklist.5.md
- sbin/firehol
Adds a `nolog` option to the `blacklist` commands for cases where the user doesn't want the blacklisting to be logged. Useful for rules which are frequently triggered.
> blacklist: add "nolog" option

- sbin/fireqos
Partial fix for #351 .
This will fail if there are multiple USB interfaces with very similar MAC addresses, but at the moment _none_ of them would work at all.
> workaround for cases where "-ifb" name gets truncated

- sbin/update-ipsets
According to https://iplists.firehol.org/?ipset=nixspam the last successful update was in september.
```
HTTP/1.1 301 Moved Permanently
Date: Fri, 25 Mar 2022 18:20:52 GMT
Server: Apache
Location: https://www.nixspam.net/?old_domain=true
Content-Type: text/html; charset=iso-8859-1
HTTP/1.1 200 OK
Date: Fri, 25 Mar 2022 18:20:47 GMT
Server: Apache
Last-Modified: Fri, 25 Mar 2022 18:15:01 GMT
ETag: "212a1-5db0ef0ed09f2"
Accept-Ranges: bytes
Content-Length: 135841
Content-Type: application/x-gzip
```
> update-ipsets: fix NiX Spam URL

- sbin/update-ipsets
The dshield file can currently be downloaded only using http**s**.
> update-ipsets: change dshield url

- sbin/update-ipsets
Removing the DShield Top 1000 lists. It is not suitable to be used as a blocklist and has been discontinued. See https://dshield.org/api/sources/attacks/1000/
> Remove dshield top 1000 list

- sbin/update-ipsets
A lot of lists are not available anymore and they have been removed.
Now optionally uses a new feature of `iprange` which allows it to work on directories with hundreds of thousands of retention files per ipset (used by the histogram of the website).
> update-ipsets cleanup

- doc/services-db.data
Description: fix: upstream doc: confusing quotes
Quote a couple of double-quotes with single quotes
to avoid pandoc (3.1.11.1) confusion.
This patch might be a workaround but not solid fix.
Origin: vendor, Debian
Author: Jerome Benoit <calculus@rezozer.net>
Last-Update: 2025-04-13
> fix confusing quotes in doc

- sbin/update-ipsets
- Ignore empty country file '.zone' in ipdeny_country
- Update URL for ip2location_country (use https:)
- Drop spamhaus_edrop list (discontinued, merged into 'drop' list)
> Various update-ipsets fixes
